// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyyk3c95xPeQ87Q9BaBkcp0fpgX7KM4ks',
    appId: '1:946720798027:web:6e1092d04bab4920f124ce',
    messagingSenderId: '946720798027',
    projectId: 'instagram-clone-1ec4c',
    authDomain: 'instagram-clone-1ec4c.firebaseapp.com',
    storageBucket: 'instagram-clone-1ec4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtiViWWRA1HoAmatI-qBQp0iMcTbZxiI',
    appId: '1:946720798027:android:39bcd449fe2849f8f124ce',
    messagingSenderId: '946720798027',
    projectId: 'instagram-clone-1ec4c',
    storageBucket: 'instagram-clone-1ec4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpEAgFEYBb129BaF_PcIFu6KKSKwUbcec',
    appId: '1:946720798027:ios:47201744e5fb6712f124ce',
    messagingSenderId: '946720798027',
    projectId: 'instagram-clone-1ec4c',
    storageBucket: 'instagram-clone-1ec4c.appspot.com',
    iosClientId: '946720798027-bcr8sqdbaenl258dit6dt4s7qt8grfcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
